### ISSUE TITLE
the python version of this repo?

### ISSUE THREAD

**Issue by batmansdu** [ericyangyu/PPO-for-Beginners#10]
Hi Yu
   GOOD work! your tutorials save me lots of time. But which version of python you use?

**Comment by ericyangyu** [comment]
Thanks! Glad it helped :) I think python3.7? Though any python3.* versions should work I think.

**Comment by ChloeKiwi** [comment]
> Thanks! Glad it helped :) I think python3.7? Though any python3.* versions should work I think.

python3.7 seems to fail when installing some packages in requirements.txt
