### ISSUE TITLE
ImportError: libboost_filesystem.so.1.65.1 in Collab

### ISSUE THREAD

**Issue by RobinSeaside** [ericyangyu/PPO-for-Beginners#11]
Did anyone run into this error?
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/15882311/227223845-ea3e0079-ef52-4cdd-ae7d-a46fef2b4335.png">

**Comment by ericyangyu** [comment]
Does [this ](https://stackoverflow.com/questions/4581305/error-while-loading-shared-libraries-libboost-system-so-1-45-0-cannot-open-sha) help?
