### ISSUE TITLE
covariance matrix

### ISSUE THREAD

**Issue by keinccgithub** [ericyangyu/PPO-for-Beginners#6]
I don't know why you choose the determinate covariance matrix?
The covariance matrix should be learned by actor network.

**Comment by ericyangyu** [comment]
The covariance matrix is used to determine the shape of our multivariate gaussian distribution around some mean (which is generated by the actor network); this distribution gives us a way to explore values around our mean. The actor network is not trying to learn the covariance matrix, but rather, it's trying to learn the general vicinity an action should be sampled from given a state such that the future expected return is maximized.

**Comment by luistung** [comment]
Since a fixed covariance matrix is used, the entropy_loss does not change, making the entropy_loss useless.
